### ISSUE TITLE
BoundingBoxTree() doesn't work in parallel on MeshView meshes

### ISSUE THREAD

**Issue by justinlaughlin** [justinlaughlin/stubs#38]
Probably will require a fork of dolfin.

Detailed explanation of issue here:
https://fenicsproject.discourse.group/t/assembly-on-mixed-domain-hangs-segfaults-in-parallel-dependent-on-partitioning/7583/2

**Comment by jorgensd** [comment]
It crashes for an even smaller problem:
```
import dolfin as d
# Create a mesh
mesh = d.UnitCubeMesh(40,40,40)
z_slice = 0.5 # value of z we use to demaracate the different subvolumes
mesh.coordinates()[:,2] *= 4 # something about partitioning leads to hanging
mesh.init()

# define mesh functions
mf3 = d.MeshFunction("size_t", mesh, 3, 0)
mf2 = d.MeshFunction("size_t", mesh, 2, 0)
for c in d.cells(mesh):
    mf3[c] = ( c.midpoint().z() < z_slice+d.DOLFIN_EPS )*1

for f in d.facets(mesh):
    mf2[f] = (z_slice-d.DOLFIN_EPS <= f.midpoint().z() <= z_slice+d.DOLFIN_EPS)*1

# Create submeshes using MeshView
mesh0 = d.MeshView.create(mf3, 1)
print(mesh0.ordered())
mesh0.order()

V0 = d.FunctionSpace(mesh0, "CG", 1)
```
which fails during dofmap creation (node-reordering in dofmapbuilder)
https://bitbucket.org/fenics-project/dolfin/src/master/dolfin/fem/DofMapBuilder.cpp

**Comment by jorgensd** [comment]
The issue is down to having no cells on the current process
```python
# mixed assembly mwe
import dolfin as d
# Create a mesh
mesh = d.UnitCubeMesh(40,40,40)
z_slice = 0.5 # value of z we use to demaracate the different subvolumes
mesh.coordinates()[:,2] *= 4 # something about partitioning leads to hanging
mesh.init()

# define mesh functions
mf3 = d.MeshFunction("size_t", mesh, 3, 0)
for c in d.cells(mesh):
    mf3[c] = ( c.midpoint().z() < z_slice+d.DOLFIN_EPS )*1

# Create submeshes using MeshView
mesh0 = d.MeshView.create(mf3, 1)
print(d.MPI.comm_world.rank,[mesh0.num_entities(i) for i in range(mesh0.topology().dim()+1)])

# function space and function
#V0 = d.FunctionSpace(mesh0, "CG", 1)
```
Cannot create function space if no cell on process (i.e. using 3 processes).
This means that the problem can be reduce to a mesh
```python
mesh = d.UnitCubeMesh(1,1,3)
```
and running with only two processes, or a
`1x1x1` mesh in serial (i.e. create an empty mesh view)
```python
0 [0, 0, 0, 0]
Traceback (most recent call last):
  File "/root/shared/debug_bb.py", line 19, in <module>
    V0 = d.FunctionSpace(mesh0, "CG", 1)
  File "/usr/lib/python3/dist-packages/dolfin/function/functionspace.py", line 33, in __init__
    self._init_convenience(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/dolfin/function/functionspace.py", line 100, in _init_convenience
    self._init_from_ufl(mesh, element, constrained_domain=constrained_domain)
  File "/usr/lib/python3/dist-packages/dolfin/function/functionspace.py", line 50, in _init_from_ufl
    dolfin_dofmap = cpp.fem.DofMap(ufc_dofmap, mesh)
RuntimeError: 

*** -------------------------------------------------------------------------
*** DOLFIN encountered an error. If you are not able to resolve this issue
*** using the information listed below, you can ask for help at
***
***     fenics-support@googlegroups.com
***
*** Remember to include the error message listed below and, if possible,
*** include a *minimal* running example to reproduce the error.
***
*** -------------------------------------------------------------------------
*** Error:   Unable to re-order graph using SCOTCH.
*** Reason:  Error during re-ordering.
*** Where:   This error was encountered inside SCOTCH.cpp.
*** Process: 0
*** 
*** DOLFIN version: 2019.2.0.dev0
*** Git changeset:  fe449b81dbfe464d6d5e264496289cccb98bddf9
```
